from src.config import settings


class SchedulerConfig:
    ALERT_EVALUATION_INTERVAL_SECONDS = settings.ALERT_EVALUATION_INTERVAL_SECONDS
    OFFLINE_TIMEOUT_SECONDS = settings.OFFLINE_TIMEOUT_SECONDS
    METRICS_RETENTION_DAYS = settings.METRICS_RETENTION_DAYS
    METRICS_CLEANUP_INTERVAL_SECONDS = settings.METRICS_CLEANUP_INTERVAL_SECONDS


scheduler_config = SchedulerConfig()
